### ISSUE TITLE
Future data?

### ISSUE THREAD

**Issue by rvoitenko** [daenney/vattenfall#2]
Hi,

do you think it's possible to fetch future data from Vattenfall and display it somehow in Grafana?

**Comment by daenney** [comment]
We do have a whole day's worth of data and you can set a time range in Grafana to be in the future. From a display perspective I suppose it's possible. But future data doesn't really map to what Prometheus is doing, that's always past-up-to-now. We'd have to fake some kind of time series as being in the past and dealing with the scrape interval too.

There is the Grafana JSON plugin https://grafana.com/grafana/plugins/simpod-json-datasource/ which might be usable for this purpose instead. We could add a separate endpoint to this exporter exposing future data in this format and hope that's graphable.

**Comment by rvoitenko** [comment]
FYI, I've made another tool to export the data into InfluxDB and show it as future forecast  - https://github.com/rvoitenko/vattenfall-to-influxdb

**Comment by daenney** [comment]
I ended up adding this in 3fd00ecbb143264400f373fbbc9a2b08cb11f696. Now you can graph it in Grafana directly without needing to ingest the data somewhere else too.

**Comment by rvoitenko** [comment]
it's a great feature!
However, I have a small issue with it, when I run the command with specific region, for example:
`vattenfall  -output.http=":9000" -region SN3`

It does not honor region parameter and display all regions(SN1-SN3) informations at /forecast.
It make it little bit difficult to make graph in Grafana only for single region, at least I don't know how.  
Do you know what can be the issue?

**Comment by daenney** [comment]
Oh yeah, sorry. It takes it as a URL parameter, you can set a Parameter of `region` and then `SN3` and it'll limit. But that's silly actually, I should be reusing the region that folks are already passing in. Let me go in and fix that.

**Comment by daenney** [comment]
Here we go: 9447559763f0b88afb063df7dd1de36d1abda3aa. v0.3.2 is getting built right now.

**Comment by rvoitenko** [comment]
works like a charm, thanks!
